apiVersion: v1
kind: Namespace
metadata:
  name: smart-home

---

apiVersion: v1
kind: Service
metadata:
  name: openhab-services
  namespace: smart-home
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.214
  ports:
    - targetPort: 8080            # Pod port
      port: 8080                  # Service port
      protocol: TCP
  selector:
    app: openhab  # Kept selector simple with primary label

---

apiVersion: v1
kind: Pod
metadata:
  name: openhab-pod
  namespace: smart-home
  labels:
    app: openhab
    type: smart-home
spec:
  restartPolicy: Always  # Added restart policy
  containers:
    - name: openhab
      image: openhab/openhab:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
        - containerPort: 8443
      volumeMounts:
        - mountPath: /openhab/conf
          name: conf
        - mountPath: /openhab/addons
          name: addons
        - mountPath: /openhab/userdata
          name: userdata
    
  volumes:
    - name: conf
      hostPath:
        path: /home/lucas/apps/openhab/conf
    - name: addons
      hostPath:
        path: /home/lucas/apps/openhab/addons
    - name: userdata
      hostPath:
        path: /home/lucas/apps/openhab/userdata
