# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openhab
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-pvc
  namespace: openhab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhab
  namespace: openhab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhab
  template:
    metadata:
      labels:
        app: openhab
    spec:
      containers:
        - name: openhab
          image: openhab/openhab:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          volumeMounts:
            - name: openhab-storage
              mountPath: /openhab/conf
            - name: openhab-userdata
              mountPath: /openhab/userdata
      volumes:
        - name: openhab-storage
          persistentVolumeClaim:
            claimName: openhab-pvc
        - name: openhab-userdata
          persistentVolumeClaim:
            claimName: openhab-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openhab-service
  namespace: openhab
spec:
  selector:
    app: openhab
  type: LoadBalancer
  loadBalancerIP: 192.168.1.231
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 443
      targetPort: 8443
      name: https
